language: csharp
solution: Templarbit.sln
install:
  - nuget restore Templarbit.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Templarbit.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Templarbit.UnitTests/bin/Release/Templarbit.UnitTests.dll
